---
exp_name: qm8_ada_lanczos_net
exp_dir: exp/qm8_ada_lanczos_net
runner: QM8Runner
use_gpu: true
gpus: [0]
seed: 1234
# seed: 5678
# seed: 9012
dataset:
  loader_name: QM8Data
  name: chemistry
  data_path: data/QM8/preprocess
  meta_data_path: data/QM8/QM8_meta.p
  num_atom: 70
  num_bond_type: 6  
model:
  name: AdaLanczosNet
  short_diffusion_dist: [1, 2, 3]
  long_diffusion_dist: [5, 7, 10, 20, 30]
  num_eig_vec: 20
  use_reorthogonalization: false
  use_power_iteration_cap: false
  spectral_filter_kind: MLP
  input_dim: 64
  hidden_dim: [128, 128, 128, 128, 128, 128, 128]
  output_dim: 16
  num_layer: 7
  loss: MSE
  output_func: MLP
train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_steps: [10000]
  num_workers: 4
  max_epoch: 200
  batch_size: 64
  display_iter: 100
  snapshot_epoch: 10000
  valid_epoch: 1
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_model: None
test:
  batch_size: 64
  num_workers: 0
  test_model: exp/qm8_ada_lanczos_net/AdaLanczosNet_chemistry_2018-Dec-28-21-46-34_11666/model_snapshot_best.pth
  # test_model: exp/qm8_ada_lanczos_net/AdaLanczosNet_chemistry_2018-Dec-30-11-36-25_7857/model_snapshot_best.pth
  # test_model: exp/qm8_ada_lanczos_net/AdaLanczosNet_chemistry_2018-Dec-30-11-36-48_8366/model_snapshot_best.pth
