---
exp_name: qm8_lanczos_net
exp_dir: exp/qm8_lanczos_net
runner: QM8Runner
use_gpu: true
gpus: [0]
seed: 1234
# seed: 5678
# seed: 9012
dataset:
  loader_name: QM8Data
  name: chemistry
  data_path: data/QM8/preprocess
  meta_data_path: data/QM8/QM8_meta.p
  num_atom: 70
  num_bond_type: 6  
model:
  name: LanczosNet
  # short_diffusion_dist: []
  # long_diffusion_dist: [1, 2, 3, 5, 7, 10, 20, 30]
  short_diffusion_dist: [3, 5, 7]
  long_diffusion_dist: [10, 20, 30]  
  num_eig_vec: 20
  spectral_filter_kind: MLP  
  input_dim: 64
  hidden_dim: [128, 128, 128, 128, 128, 128, 128]
  output_dim: 16
  num_layer: 7
  loss: MSE
  output_func: MLP  
train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_steps: [10000]
  num_workers: 4
  max_epoch: 200
  batch_size: 64
  display_iter: 100
  snapshot_epoch: 10000
  valid_epoch: 1
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_model: None
test:  
  batch_size: 64
  num_workers: 0
  test_model: exp/qm8_lanczos_net/LanczosNetFixBasisChem_chemistry_2018-Oct-02-11-55-54_25460/model_snapshot_best.pth
  # test_model: exp/qm8_lanczos_net/LanczosNetFixBasisChem_chemistry_2018-Oct-02-14-04-53_18123/model_snapshot_best.pth
  # test_model: exp/qm8_lanczos_net/LanczosNetFixBasisChem_chemistry_2018-Oct-02-15-53-14_20776/model_snapshot_best.pth
